# This workflow will build a Java project with Ant for a NetBeans project
# Optimized for the ITS-Projekt NotizDesktop application

name: Java CI with Ant

on:
  push:
    branches: [ "main", "GUI-HTML-Ant" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Download dependencies
      run: |
        mkdir -p lib
        wget -O lib/mysql-connector-java-8.0.23.jar https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.23/mysql-connector-java-8.0.23.jar
        wget -O lib/spring-security-crypto-5.7.2.jar https://repo1.maven.org/maven2/org/springframework/security/spring-security-crypto/5.7.2/spring-security-crypto-5.7.2.jar
        wget -O lib/slf4j-api-1.7.36.jar https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar
        wget -O lib/logback-classic-1.2.12.jar https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.2.12/logback-classic-1.2.12.jar
        wget -O lib/logback-core-1.2.12.jar https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.2.12/logback-core-1.2.12.jar
    
    - name: Build with Ant
      run: ant clean compile jar
    
    - name: List compiled artifacts
      run: |
        echo "=== Compiled Classes ==="
        find build -name "*.class" | sort
        echo "=== Generated JARs ==="
        find dist -name "*.jar" | sort
